First part
Baldinini/jv-create-annotation pull request #1
Opened 2021-01-06 14:35 UTC by Baldinini

2021-01-06 16:27 UTC, IgorBochkor approved these changes

2021-01-08 09:31 UTC, KseniiaMakarova requested changes

2021-01-08 09:31 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +    BetDao betDao = new BetDaoImpl();
what is missing?

2021-01-08 09:31 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            } catch (NumberFormatException e) {
what about ArrayIndexOutOfBoundException? let’s catch it here as well

2021-01-08 09:31 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            betDao.add(bet);
let’s save  the bet if it is not null

2021-01-08 09:31 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            System.out.println(bet == null ? null : bet.toString());
```suggestion
            System.out.println(bet);
```

2021-01-08 09:31 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/BetDaoImpl.java
> +
redundant empty line

2021-01-08 14:22 UTC, KseniiaMakarova requested changes

2021-01-08 14:22 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +    private static final BetDao betDao = new BetDaoImpl();
let's not make it static

2021-01-08 14:31 UTC, KseniiaMakarova approved these changes

2021-01-10 14:53 UTC, merged